---
app_name: devops-app
docker_image: "{{ dockerhub_username }}/{{ app_name }}"
docker_image_tag: latest
app_port: 5000
app_container_port: 8000
app_container_name: "{{ app_name }}"
app_restart_policy: unless-stopped
app_healthcheck_path: /health
app_environment: {}
